### ISSUE TITLE
/tmp/ccchbaGk.s:33389: Error: no such instruction: `tpause %ecx'

### ISSUE THREAD

**Issue by HorizonLiang** [oneapi-src/oneTBB#1023]

**Comment by bsergean** [comment]
I have the same compile error on Ubuntu 18.04

**Comment by pavelkumbrasev** [comment]
There is no description to investigate this issue. @bsergean Could you please try the latest release?

**Comment by isaevil** [comment]
@bsergean please refer to #859, maybe it is relatable. What version of compiler and `binutils` package do you use?

**Comment by bsergean** [comment]
Yeah you guys have already closed this as won't fix, which I totally understand because a large support matrix is really painful.

But basically we need to build with gcc-11 on a standard ubuntu-18.04 normal box, and as you said upgrading binutils is the solution but it isn't as easy to do I think as changing the default version of gcc which is more common.

I will try to compile with clang, to see if out of curiosity the problem manifest too.
