### ISSUE TITLE
Need natvis file

### ISSUE THREAD

**Issue by lekeshibai** [oneapi-src/oneTBB#1231]
I would like to provide natvis files to facilitate debugging in visual studiodio

**Comment by sarathnandu** [comment]
Thank you for your interest in contributing to the oneTBB project. While I'm not very familiar with natvis files myself, a quick online search suggests that they can greatly enhance the debugging experience in Visual Studio. I believe it's a good idea to create a pull request with your changes so that you can receive feedback from other contributors.

Just to clarify, we don't offer a dedicated Visual Studio solution for TBB. Instead, we use a CMake-based build system, and you can generate a Visual Studio solution for oneTBB and its examples using the CMake generator. If you have any questions or need assistance, feel free to ask, and I'll be happy to help!"

**Comment by VirtualTim** [comment]
Personally, I'd find a natvis for `concurrent_hash_map` really helpful.

**Comment by sarathnandu** [comment]
Closing this issue based on previous comments. Feel free to contribute Natvis file and link to this issue in the future.
