### ISSUE TITLE
[2019~u3/power8] massive amount of errors during testing

### ISSUE THREAD

**Issue by cdluminate** [oneapi-src/oneTBB#124]
https://buildd.debian.org/status/fetch.php?pkg=tbb&arch=ppc64el&ver=2019%7EU3-1%7Eexp1&stamp=1549125698&raw=0

```
...
ERROR for Spin RW Mutex at 8378: read,  lock kept, impl/expl
ERROR: 11048!=11049
ERROR for Spin RW Mutex at 264654: read,  lock kept, impl/expl
ERROR: 11049!=11050
ERROR for Spin RW Mutex at 389187: read, upgrade, lock kept, expl/impl
ERROR: 11049!=11050
ERROR for Spin RW Mutex at 389188: read,  lock kept, expl/impl
ERROR: 11049!=11050
ERROR for Spin RW Mutex at 389189: read,  lock kept, expl/impl
ERROR: 11049!=11050
ERROR for Spin RW Mutex at 389190: read,  lock kept, expl/impl
ERROR: 11049!=11050
ERROR: 11050!=11051
ERROR for Spin RW Mutex at 8379: read, upgrade, lock kept, impl/expl
ERROR: 11051!=11052
ERROR for Spin RW Mutex at 389191: write, downgrade, lock kept, expl/impl
...
```

**Comment by cdluminate** [comment]
I think the same problem also exists in 2018~u6: https://buildd.debian.org/status/fetch.php?pkg=tbb&arch=ppc64el&ver=2018%7EU6-4&stamp=1544650155&raw=0

**Comment by akukanov** [comment]
Thanks for the report. As far as I can see, the issue can be traced back even to TBB 4.2. The good thing is that it can be ignored, because the test is for an old, unused version of code that only exists for backward compatibility with really old TBB binaries. But, it does make sense to skip these tests and avoid so many useless messages in the log.

**Comment by anton-potapov** [comment]
It seems that this is not relevant to oneTBB due to significant changes in the code base (revamp)
