### ISSUE TITLE
Update Node using TBB Nodes

### ISSUE THREAD

**Issue by MasterBe** [oneapi-src/oneTBB#1315]
Hello, is there a way to have joiner/indexer or composite node with an update policy? The update policy has the requirement:
1. The output is ready once at least one port has a value.
2. Mechanism to check if a port is ready at the receiving node e.g. null pointer or default constructor or user defined invalid value or a flag true or false indicating if the port is ready
3. If a port has only one value, this value is conserved and is sent once another port with new value is ready (if all ports hold the same old message, then no updates).

Example:
1. Update node with two ports 1 and 2.
2. Value x1 is pushed into port 1 => the node is ready to send updates with "pair" {x1, nullptr} while keeping x1 in the queue.
3. Value x2 arrives at port 1 => the node is ready and sends {x2, nullptr}, x1 is overwritten and x2 is conserved
4. Value y1 arrives at port 2 => the node is ready and sends {x2, y1} and x2 and y1 are conserved
5. Value x3 arrived at port 1 => the node is ready and sends {x3, y1} and x3 and y1 are conserved

This looks like combination of either joiner/indexer or composite and overwrite_node.

**Comment by aleksei-fedotov** [comment]
I have similar thinking wrt `overwrite_node`. This type of the node is necessary in order to conserve the last value pushed to it.
The other behavior is to form a message whenever the new update comes to one of the ports.

I have been thinking about a `join_node` with reserving policy with the `N` number of input ports, where `N-1` port is connected to `overwrite_node` predecessors of the `join_node`, whereas the last `N`-th port gets connected to, let's say, a `buffer_node`. The messages in this `buffer_node` serve as flags, denoting that the update has happened and that the `join_node` may proceed with forming a tuple from all of the input ports.
Also, in this graph there should be a node, e.g., a `multifunction_node`, that serves as a predecessor to `overwrite_node`s and a `buffer_node` that will send at least two messages:
1. The updated value to one of the `overwrite_node`s
1. The flag message to the `buffer_node` indicating the update has happened.

**Comment by sarathnandu** [comment]
I believe the above comment answers your question. Feel free to re-open the issue if you need more help.
