### ISSUE TITLE
Install directory

### ISSUE THREAD

**Issue by shersoni610** [oneapi-src/oneTBB#222]
Hello,

I could not see CMakeList.txt but only Makefile. How do I specify install directory?

**Comment by AlexVeprev** [comment]
Hi @shersoni610,

TBB doesn't have full-featured CMake build system, that's why there is no CMakeLists.txt. On the other hand there is no support for installation in Makefiles, so you can't specify install directory.

Related issue: https://github.com/intel/tbb/issues/175.

**Comment by shersoni610** [comment]
There must be some rationale behind not using standard (or widely accepted norms) way to build thing up for non-experts like us.

**Comment by AlexVeprev** [comment]
Installation is usual but not necessary part of build process: you can build TBB, source tbbvars script to add TBB paths to environment and use TBB without installation.

Sometimes using `make install` is considered as a bad practice since it is hard to revert changes after it.

Probably you don't need to build TBB on your own. Consider using pre-built version from official or 3d-party repo/channel. In that case all the installation/uninstallation things are handled by respective package manager (apt, yum, conda, brew, etc.).
For example, [here](https://software.intel.com/en-us/articles/installing-intel-free-libs-and-python-apt-repo) you can find instructions for official APT repository and [here](https://repology.org/project/tbb/versions) is a list of TBB packages from 3d-party maintainers.

If you have other questions/concerns regarding the issue, please describe your use case.

**Comment by AlexVeprev** [comment]
Looks like the issue may be closed. Further discussions about install instructions should be done in scope of #232.
