### ISSUE TITLE
TBBConfig.cmake. Where it is?

### ISSUE THREAD

**Issue by shersoni610** [oneapi-src/oneTBB#225]
Hello

I build TBB using source code using the Makefile. Now I am trying to 
build ParallelSTL which is asking for TBBConfig.cmake. I could not
find it under the source code. How should I generate it?

**Comment by AlexVeprev** [comment]
Hi @shersoni610,

TBB Makefiles don't support generation of TBBConfig.cmake.

There are a few ways to get TBBConfig. One of the simplest is to use TBB package from [Releases](https://github.com/intel/tbb/releases) page, e.g. [tbb-2020.1-lin.tgz](https://github.com/intel/tbb/releases/download/v2020.1/tbb-2020.1-lin.tgz).

It contains TBBConfig in the `tbb/cmake` folder. So you can unpack it and run something like `cmake -DTBB_DIR=<unpacked-tbb-package>/tbb/cmake <parallel-stl-dir>`.

Please let me know if the above approach is not suitable for you.

----
Documentation for CMake support in TBB is available [here](https://github.com/intel/tbb/tree/tbb_2020/cmake#binary-package-integration). It includes some examples and instructions how to generate TBBConfig.

**Comment by hradec** [comment]
Just in case someone want's to generate the `TBBConfig.cmake` file from the actual source (like myself) instead of downloading it from the Releases, this seems to be how you do it properly: 

```
cmake -DTBB_ROOT=<folder where tbb /include and /lib is>   -DTBB_OS=Linux -P cmake/tbb_config_generator.cmake
```
The `cmake/tbb_config_generator.cmake` is a cmake script that generates the `TBBConfig.cmake` for you, and puts it in a cmake folder in the `TBB_ROOT` folder for you. 

I really don't get it why TBB Makefile doesn't implement a simple `make install` like everyone else that would populate a installation folder (INSTALL_PREFIX) with includes, libraries and the cmake stuff.

**Comment by AlexVeprev** [comment]
Hi @hradec, oneTBB has CMake-based build system, it provides stuff like `make install`, you can find details here: https://github.com/oneapi-src/oneTBB/blob/master/INSTALL.md

If you still need to create configs for TBB 2020 or older, I'd suggest to take a look at tbb_config_installer.cmake, it was intended for package maintainers and allows to generate configs in more flexible way than tbb_config_generator.cmake that  was intended for TBB GitHub packages. Please take a look at https://github.com/oneapi-src/oneTBB/tree/tbb_2020/cmake#tbbinstallconfig
