### ISSUE TITLE
Pipeline being deprecated without suitable replacement

### ISSUE THREAD

**Issue by jeremyong** [oneapi-src/oneTBB#228]
The most recent release has marked both `pipeline` and `thread_bound_filter` as deprecated, however, they are not entirely subsumed by `parallel_pipeline`. A common use case is managing a task that _must_ run on the main thread due to OS restrictions. For example, handling various window events _must_ occur on the thread that created the window. How should users migrate code to accommodate this usecase?

**Comment by aleksei-fedotov** [comment]
According to TBB revamp topic written [here](https://software.intel.com/en-us/forums/intel-threading-building-blocks/topic/815880), for the purposes of `thread_bound_filter` [`async_node`](https://www.threadingbuildingblocks.org/docs/help/hh_goto.htm?index.htm#reference/flow_graph/async_node_cls.html) from flow graph component can be used.
From my point of view, flow graph is better suited for managing various window events.
The way I see it is that an event callback submits a task to the graph using the `try_put()` call on one of the graph nodes. In turn, the dispatching loop calls `graph::wait_for_all()` method to make sure all events are processed.

Is it acceptable scheme for handling various window events?

**Comment by jeremyong** [comment]
Thanks for the response @aleksei-fedotov . One way to manage it is to have a dedicated thread for OS events (which must be polled on the thread that created the OS window). This can communicate events to a flow graph through, say, a `concurrent_queue` talking to the flow graph's `source_node`, or with an async node.

One thing I was trying to avoid was having a dedicated thread in the first place. This would be possible if, for example, I could pin the activity of the `source_node` on a particular thread. The `wait_for_all` method you mentioned doesn't work if polling OS events happens independently of the application's main event loop (which might be rendering or doing some other activity keeping all cores occupied).

**Comment by aleksei-fedotov** [comment]
As far as I know, even `pipeline` with its `thread_bound_filter` didn't allow to avoid creation of a dedicated thread on the user side. And `async_node` is not different in this case. Its body puts the data into concurrent queue to a dedicated thread, which polls that concurrent queue once in a while. Once the message is there, the dedicated thread processes it and releases the graph. This is identical to the `async_node` example in the documentation.

So I conclude with the following two statements:
1. The implementation that uses `pipeline` and `thread_bound_filter` can be rewritten using `async_node` and `concurrent_queue`. 
2. The request in this issue is actually about improving the interface that would allow pinning the execution of the body of a particular node in the graph to a dedicated thread.

Please let me know whether I am right or wrong with each of these statements.

**Comment by akukanov** [comment]
I agree with @aleksei-fedotov that a pipeline with TBF still needed an extra thread, because `pipeline::run()` is a blocking call in the same way as `graph.wait_for_all()`.

In case the bound filter is the first in the pipeline, with flow graph the same behavior can be achieved if the main thread does the following:

- call `graph::reserve_wait()` to prevent the graph to complete until there is no more input;
- start another thread that calls `graph.wait_for_all()`;
- execute the code of the first pipeline stage on its own, without formally adding it into a graph node;
- `try_put()` the result directly to the graph node representing the second pipeline stage;
- call `graph::release_wait()` once there is no more input expected;
- join the graph processing thread.

In case the bound filter is in the middle or at the end of the pipeline, you'd still need to start a thread for running the graph, and then use `async_node` for directing the message flow from the graph to the main thread (via some buffer, such as `concurrent_queue`) and then back to the graph via the `gateway` interface of `async_node`. To prevent premature graph completion, call `gateway.reserve_wait()` in the body of `async_node` for each message, and `gateway.release_wait()` in the main thread once the message is passed back to the graph; doing it exactly this way is not mandated, but other approaches would rely on some application-specific ways to share information about graph completion.

**Comment by jeremyong** [comment]
Thanks for the responses, it seems I might have been misinformed on the capabilities of TBF. I'll proceed with an additional dedicated thread and message passing queue.
