### ISSUE TITLE
TBB repository change on Github

### ISSUE THREAD

**Issue by uilianries** [oneapi-src/oneTBB#237]
Hi!

I would like to know why the Github repository has been changed from https://github.com/intel/tbb to https://github.com/oneapi-src/oneTBB.

Also, the checksum for v2020.0 does not match between the new URL and the old one. If it's a source code snapshot and follow the same tag, why does is it different?

https://github.com/intel/tbb/archive/v2020.0.tar.gz
SHA-256: 8eed2377ac62e6ac10af5a8303ce861e4525ffe491a061b48e8fe094fc741ce9

https://github.com/oneapi-src/oneTBB/archive/v2020.0.tar.gz
SHA-256: 57714f2d2cf33935db33cee93af57eb3ecd5a7bef40c1fb7ca4a41d79684b118

/cc @danimtb @sse4

**Comment by edigaryev** [comment]
I've just hit this issue while attempting to verify https://github.com/01org/tbb/archive/2018_U6.tar.gz.

Looking at the archive contents, it seems that due to repository name change, the base directory changed too, which affected the archive metadata, and thus the checksum:

```
$ tar -tvf 2018_U6.tar.gz.old | head -n 5
drwxrwxr-x root/root         0 2018-10-09 12:12 tbb-2018_U6/
-rw-rw-r-- root/root       790 2018-10-09 12:12 tbb-2018_U6/.gitattributes
-rw-rw-r-- root/root      1036 2018-10-09 12:12 tbb-2018_U6/.gitignore
-rw-rw-r-- root/root    101273 2018-10-09 12:12 tbb-2018_U6/CHANGES
-rw-rw-r-- root/root     11357 2018-10-09 12:12 tbb-2018_U6/LICENSE
```

```
$ tar -tvf 2018_U6.tar.gz.new | head -n 5
drwxrwxr-x root/root         0 2018-10-09 12:12 oneTBB-2018_U6/
-rw-rw-r-- root/root       790 2018-10-09 12:12 oneTBB-2018_U6/.gitattributes
-rw-rw-r-- root/root      1036 2018-10-09 12:12 oneTBB-2018_U6/.gitignore
-rw-rw-r-- root/root    101273 2018-10-09 12:12 oneTBB-2018_U6/CHANGES
-rw-rw-r-- root/root     11357 2018-10-09 12:12 oneTBB-2018_U6/LICENSE
```

If you do not take that base directory into the consideration, the rest of the contents seem to be identical:

```
$ diff -qr tbb-2018_U6.old/ oneTBB-2018_U6.new/
$ 
```

**Comment by tbbdev** [comment]
The repo has been migrated to ensure that developers are aware that TBB is part of the exciting new [oneAPI initiative](https://www.oneapi.com/open-source/).

Content of code snapshots for the tags has not been changed. Likely checksums don't match because of changed repository location. @edigaryev, thank you for checking and detailed explanation!

**Comment by uilianries** [comment]
Thanks a lot for the explanation!
