### ISSUE TITLE
Location of install script

### ISSUE THREAD

**Issue by varunagrawal** [oneapi-src/oneTBB#238]
I have an update that allows the install script to work on both Bash and ZSH without changes, but I can't find the script location.

Can someone please point it to me so I can create the PR?

**Comment by AlexVeprev** [comment]
Hi @varunagrawal, could you please clarify which script you mean? tbbvars?

If yes:

- tbbvars for binaries built from open-source packages are generated on the fly using https://github.com/oneapi-src/oneTBB/blob/tbb_2020/build/generate_tbbvars.sh
- tbbvars from prebuilt packages (available on [the releases page](https://github.com/oneapi-src/oneTBB/releases)) are not available in the repo, so if you have proposals there you can just add/attach them here into this issue.

**Comment by varunagrawal** [comment]
Yes I mean the tbbvars. Thank you @AlexVeprev. That's surprising that the script isn't in the repo. Doesn't it sort of defeat the purpose of being open source?

**Comment by AlexVeprev** [comment]
Having these files only in binary packages is rather a historical (process) reason than intentional decision I believe. It doesn't mean these files are "closed", they are "open" too, but in a bit different manner. Anyway oneAPI initiative seems to be a good reason to make things more consistent and clear. There is a recent beta release on [onetbb_2021](https://github.com/oneapi-src/oneTBB/tree/onetbb_2021) branch - [oneTBB 2021.1-beta05](https://github.com/oneapi-src/oneTBB/releases/tag/v2021.1-beta05). Will it be suitable for you if the updates are applied in one of future releases in scope of the new branch (including https://github.com/oneapi-src/oneTBB/issues/232)?

**Comment by varunagrawal** [comment]
Yes that is an excellent solution going forward. Thanks for pointing me in the right direction.

**Comment by AlexVeprev** [comment]
Finally the scripts are in the repo:
https://github.com/oneapi-src/oneTBB/blob/master/integration/linux/env/vars.sh
https://github.com/oneapi-src/oneTBB/blob/master/integration/mac/env/vars.sh
https://github.com/oneapi-src/oneTBB/blob/master/integration/windows/env/vars.bat

I'm closing the issue as done, but @varunagrawal, feel free to reopen it or create a new one if you still have concerns.

BTW, I see the original initiative was to make vars.sh working with ZSH, now it is supported as well.

**Comment by varunagrawal** [comment]
Thanks @AlexVeprev. Glad to see the updates have already been pushed.
