### ISSUE TITLE
Provide a way to handle thread creation errors

### ISSUE THREAD

**Issue by Lastique** [oneapi-src/oneTBB#255]
We are using TBB in an application that may potentially work in high load conditions, and may occasionally hit the system limits on the number of threads and processes. In our code base we handle this condition gracefully, but TBB internally does not handle this and simply terminates the process in case of thread creation failure. We need a way to handle TBB thread creation failures.

For this, we need to specify explicitly the point when the internal threads are created. There used to be `task_scheduler_init` class that could be used for this purpose, but it is currently deprecated. We would be fine if this class was un-deprecated and modified to indicate thread creation errors e.g. with an exception. A different class with the same effect would be fine as well.

Also, side note, [`exit(1)`](https://github.com/oneapi-src/oneTBB/blob/60b7d0a78f8910976678ba63a19fdaee22c0ef65/src/rml/server/thread_monitor.h#L205) is not the proper way to abort the application as it terminates without a signal. The preferred way to abort is `abort()`, as it generates a signal, which can be caught and processed e.g. by collecting a backtrace, which we do in our application.

**Comment by alexey-katranov** [comment]
I agree that `exit(1)` is not the proper way (at least `1` can be considered as non-error return code on some platforms). Is `std::terminate` suitable solution? E.g. `std::set_terminate` can be used to catch the error.
As for `task_scheduler_init`, it is not suitable for that purpose because it is not a synchronization point and does not guarantee the thread pool creation (the thread pool is created lazily). So, the exception might happen later than `task_scheduler_init` initialization or even on another thread. Moreover, in some cases thread pool can create additional threads later.

**Comment by Lastique** [comment]
> Is `std::terminate` suitable solution?

`std::terminate` is used for exception handling, so it may interfere if someone is using it for that purpose. I suppose, you could call `std::terminate` as part of throwing a TBB exception indicating thread creation failure. The default `std::terminate` handler calls `abort`, so that's good. So as far as abnormally terminating the process goes, `std::terminate` is suitable and definitely better than `exit(1)`.

> As for `task_scheduler_init`, it is not suitable for that purpose because it is not a synchronization point and does not guarantee the thread pool creation (the thread pool is created lazily).

I see. In that case we need a way to preemptively force creation of all threads in the thread pool, so we can catch potential errors at that point. That API should indicate errors in a more traditional way (e.g. with an exception) rather than `std::terminate`.

> Moreover, in some cases thread pool can create additional threads later.

Could you clarify in what cases that can happen? Can it be avoided?

**Comment by alexey-katranov** [comment]
> I suppose, you could call std::terminate as part of throwing a TBB exception indicating thread creation failure.

The main problem with exceptions in a parallel runtime like TBB that it might happen outside any user context. I.e. some worker thread might throw an exception when trying to create some other worker thread and there is no way for the user to catch it (beside with a debugger). Instead of explicit `std::terminate` we can use `noexcept` attribute for the thread function and use exceptions to indicate thread creation failures. So, if an exception occurs during parallel algorithm execution it will be caught to the `task_group_context` of the algorithm and rethrown on the waiting thread. If the exception is outside the user context, the stack unwinding will reach the thread function and due to semantics of `noexcept` we will have `std::terminate`.

> Could you clarify in what cases that can happen? Can it be avoided?

There are multiple reasons:
1. The `max_allowed_parallelism` is increased with the `global_control`.
1. There is a down side of relaxed thread notification between the arena and the thread pool. In some cases, a thread might leave the arena while another request for the threads comes. It might lead to a situation that the leaving thread is not counted yet by the thread pool and a new thread is created.

**Comment by Lastique** [comment]
> we can use `noexcept` attribute for the thread function

Note that `noexcept` is C++11, so you might not have it if you maintain compatibility with C++03. I think, calling `std::terminate` directly should be fine.

The main problem with `std::terminate` that can happen literally at any point is that it can't be handled other than by terminating the process. And this can happen while useful and possibly critical work is being done.

Would it be possible to:

1. Provide API to explicitly create threads upon user's request. That API could indicate error with an exception or error code. This includes `global_control` - if it creates threads, it indicates errors with an exception.
2. Suppress thread creation errors when they are not led by a user context. If a thread cannot be created, that is fine, it just limits the level of parallelism. At the worst case, any threaded operation can be executed exclusively by user's threads. New threads can be attempted to be created later (on later parallel operations) to allow the system to recover from a temporary limitation.
3. If thread creation is led by a user call other than p.1, make the behavior configurable so that the error is either ignored (i.e. the behavior is similar to p.2), or an exception is thrown, or `std::terminate` is called.

If you choose so, you could make that the configuration described in p.3 also applies to p.1 as well; that would be fine.

I know this sounds complicated, but this would allow us to handle these errors at select places, where no useful work is being done and ignore in other places, while maintaining the system alive.

**Comment by Lastique** [comment]
Note that when work is being done by a TBB thread on behalf on the user's call, you can pass exceptions between threads using `std::current_exception` and `std::rethrow_exception`, though that is only possible since C++11. I suppose, you should already be doing something like this if you're handling exceptions thrown in user's code.

I would be fine if in p.3. in the above there would be no option of throwing an exception. In our application we will likely choose to ignore thread creation errors on parallel operations.

**Comment by alexey-katranov** [comment]
> Note that noexcept is C++11, so you might not have it if you maintain compatibility with C++03.

C++03 is deprecated as a part of [TBB Revamp](https://software.intel.com/content/www/us/en/develop/articles/tbb-revamp.html)

> Provide API to explicitly create threads in the thread pool upon user's request. That API could indicate error with an exception or error code. This includes global_control - if it creates threads, it indicates errors with an exception.

It is quite complicated with the current design. I would consider that option only if the `std::terminate` solution is not enough.

> Suppress thread creation errors when they are not led by a user context. 

It is not easy to check if thread creation is led by a user context of not. The thread pool logic is highly isolated from tasking logic. Logically, thread creation is triggered with user requests; however, the threads are created in parallel by just created threads, so only the first thread is in the user context while other are just created.

> At the worst case, any threaded operation can be executed exclusively by user's threads.

Enqueue tasks require at least one thread to be created (so there might be no any user threads). We need to differentiate that case; otherwise, some user expectations might be broken.

> The main problem with std::terminate that can happen literally at any point is that it can't be handled other than by terminating the process. And this can happen while useful and possibly critical work is being done. This is a real problem for us.

Is it feasible to check that the required number of threads are created at the beginning of the application?

**Comment by alexey-katranov** [comment]
It seems you already answered the question:
>> Is it feasible to check that the required number of threads are created at the beginning of the application?

> In our application we will likely choose to ignore thread creation errors on parallel operations.

**Comment by Lastique** [comment]
> Is it feasible to check that the required number of threads are created at the beginning of the application?

If there is a way to force thread creation then yes, we could check if that operation succeeds early at the application startup. But you seems to be saying this is difficult to implement.

To be clear, this kind of workflow is acceptable to us:

1. Early in `main()`, call TBB to force creation of threads in thread pools.
2. If that fails, terminate the application. Ideally, we would like to be in control of the termination, e.g. to log the reason.
3. Disable any future errors wrt. thread creation in TBB. Either TBB must not create threads anymore, or failures should be silently ignored, limiting parallelism. Repeatedly attempting to create threads (ignoring failures) is ok.
4. Proceed with our tasks, possibly invoking TBB parallel constructs. No TBB failures expected here.

**Comment by Lastique** [comment]
I should add that we're not using `global_control` currently, so the level of parallelism stays constant in our case.

**Comment by alexey-katranov** [comment]
> If there is a way to force thread creation then yes, we could check if that operation succeeds early at the application startup. But you seem to be saying this is difficult to implement.

You can use barrier like approach (e.g. with `std::atomic`) to gather the required number of threads in a parallel loop. Sure, it is not safe in a general case but if you control application (main function and global constructors), you can expect `this_task_arena::max_concurrency` threads. 

>  Either TBB must not create threads anymore, or failures should be silently ignored, limiting parallelism.

It requires either some workarounds (if you can rebuild the runtime) and/or we need to figure out how to improve the interoperability between arena and thread pool to guarantee it without performance impact.

**Comment by Lastique** [comment]
> You can use barrier like approach (e.g. with `std::atomic`) to gather the required number of threads in a parallel loop.

Will this guarantee that TBB will not create any more threads later?

**Comment by Lastique** [comment]
> > You can use barrier like approach (e.g. with `std::atomic`) to gather the required number of threads in a parallel loop.
> 
> Will this guarantee that TBB will not create any more threads later?

Ping?

**Comment by alexey-katranov** [comment]
> Will this guarantee that TBB will not create any more threads later?

Unfortunately, no. The current implementation allows creation additional threads to replace threads going to sleep. It is not easy to fix in general case. If you can rebuild the TBB binary, as a temporal solution, you can set your own hard limit (I can point the place). Another workaround, if you have the only arena and do not use enqueue tasks it is possible to capture the threads to prevent them from leaving the arena and going to sleep (but it is not safe in general case because other arenas and enqueue tasks can be stuck)

**Comment by Lastique** [comment]
> If you can rebuild the TBB binary, as a temporal solution, you can set your own hard limit (I can point the place).

Yes, I can build a patched TBB. Could you point where I could do that?

> Another workaround, if you have the only arena and do not use enqueue tasks it is possible to capture the threads to prevent them from leaving the arena and going to sleep

We are not creating arenas, so I believe we're using a single arena. I don't think we're using enqueue tasks anywhere, at least not explicitly. We're using parallel algorithms (e.g. `parallel_for`). That said, I would prefer not to prohibit us using other TBB features in the future.

**Comment by alexey-katranov** [comment]
`workers_hard_limit` specifies the thread pool size limit: https://github.com/oneapi-src/oneTBB/blob/tbb_2020/src/tbb/market.cpp#L140. You can specify the number of threads that will be never exceed.

**Comment by Lastique** [comment]
Thanks, I'll take a look.

**Comment by alexey-katranov** [comment]
@Lastique, We found a solution against sporadic temporal oversubscription. It is not available in any release package yet but the fix is available in the master (we refactored the [`market::adjust_demand`](https://github.com/oneapi-src/oneTBB/blob/master/src/tbb/market.cpp#L511-L566) funtion to cap thread requests to be in the [0; max_threads] range).

**Comment by Lastique** [comment]
Good. Now we need a way to specify max_threads and also explicitly spawn all these threads.

**Comment by alexey-katranov** [comment]
It seems all discussed issues were addressed in oneTBB 2021.1: https://software.intel.com/content/www/us/en/develop/articles/intel-oneapi-threading-building-blocks-release-notes.html (see "New Features" and "Bug fixed" sections)

If there is any unresolved issues, feel free to reopen the issue.
