### ISSUE TITLE
concurrent_unordered_map size() returns huge values

### ISSUE THREAD

**Issue by claudiacorreia60** [oneapi-src/oneTBB#285]
I'm using a concurrent_unordered_map in my code, and I use multiple threads to emplace() and find() elements in the buffer. However, when I use the unsafe_erase() method I use a mutex to make sure that there aren't multiple threads trying to erase something at the same time.

When I try to run my code, there's a point where the size() method returns values like 18446744073709551615. I tried to see the code in include/tbb/internal/_concurrent_unordered_impl.h, and I think that my_element_count is being decremented when its value is 0, that's why size() returns those values.

I would like to understand why this is happening. Do I have to use a mutex to emplace() elements as well?

Thank you in advance for your help!

**Comment by kboyarinov** [comment]
Hi, @claudiacorreia60,

If I understand your use case correct, you are executing `emplace()`, `find()` and `unsafe_erase()` simultaneously, but there is a mutex, which protects multiple threads to erase elements from the map at the same moment. I am afraid that this usage is not concurrently safe because `concurrent_unordered_map` permits multiple thread to simultaneously insert and find, but not erase elements (even on only one thread). The container will work correct only if methods with `unsafe_` prefix are executed in the serial part of the application.

I guess, locking the same mutex as for `unsafe_erase` in `emplace` and `find` contexts will fix the problem, but it will substantially reduce the performance.
If concurrent erasure from the unordered map is critical for your application, consider using `tbb::concurrent_hash_map`.

**Comment by claudiacorreia60** [comment]
@kboyarinov thank you a lot for your answer!

I know that `tbb::concurrent_hash_map` allows concurrent erasures, but does it allow to perform `insert` and `find` operations concurrently?

**Comment by pavelkumbrasev** [comment]
Hi, @claudiacorreia60,
Yes, `tbb::concurrent_hash_map` support concurrent call of insert or find.

**Comment by alexey-katranov** [comment]
If the issue is still not resolved, feel free to reopen.
