### ISSUE TITLE
[CentOS8]Environment variable setting problem

### ISSUE THREAD

**Issue by iuming** [oneapi-src/oneTBB#348]
Hello, when I install TBB, I want to run it, but I can't find the `TBB_PREVIEW_GLOBAL_CONTROL` environment variable. What is the problem?How can I solve it?
```
/usr/include/tbb/global_control.h:25:2: error: #error Set TBB_PREVIEW_GLOBAL_CONTROL before including global_control.h
 #error Set TBB_PREVIEW_GLOBAL_CONTROL before including global_control.h
```

**Comment by kboyarinov** [comment]
Hello, @iuming,

If I understand correctly, you are using TBB 2020 or earlier. Please correct me if I am wrong. 
`tbb::global_control` was a preview feature in these TBB versions, but it became a fully supported since oneTBB 2021.
The easiest way to resolve the issue is to update the TBB version to oneTBB 2021.

For previous versions, the correct way to include header files with the preview features is:

`#define TBB_PREVIEW_GLOBAL_CONTROL 1`
`#include "tbb/global_control.h"`

or to define the corresponding macro using `-DTBB_PREVIEW_GLOBAL_CONTROL=1` compiler option.

**Comment by iuming** [comment]
@kboyarinov thank you very much, I will try it.

**Comment by anton-potapov** [comment]
@iuming, have you had a chance to try it ?

**Comment by anton-potapov** [comment]
@iuming, please reopen if the problem still exist on [oneTBB v2021.4.0](https://github.com/oneapi-src/oneTBB/releases/tag/v2021.4.0) or the latest master
