### ISSUE TITLE
Strange interactions between task_scheduler_init / global_control / task_arena::enqueue

### ISSUE THREAD

**Issue by e4lam** [oneapi-src/oneTBB#405]
Consider this program: https://godbolt.org/z/5c5eTY9PT
```// tbb_warning.cpp
#define  __TBB_show_deprecation_message_task_scheduler_init_H
#include <tbb/task_arena.h>
#include <tbb/task_scheduler_init.h>
#include <tbb/global_control.h>
#include <stdio.h>

const int N = 1; // single thread the app

static tbb::task_scheduler_init theTaskScheduler(N); // comment this out to see different results!

int main()
{
    printf("TBB interface version %d\n", TBB_INTERFACE_VERSION);

    printf("requesting global_control %d\n", N);
    tbb::global_control control(tbb::global_control::max_allowed_parallelism, N);
    printf("max_concurrency after global_control %d\n", tbb::this_task_arena::max_concurrency());

    tbb::task_arena attached_arena(tbb::task_arena::attach{});
    attached_arena.enqueue([]() {
        //puts("enqueued task");
    });
    printf("max_concurrency after enqueue %d\n", tbb::this_task_arena::max_concurrency());

    // On DEBUG builds, this prints:
    //     TBB Warning: The number of workers is currently limited to 0. The request for 1
    //     workers is ignored. Further requests for more workers will be silently ignored
    //     until the limit changes.
    tbb::task_arena arena(tbb::this_task_arena::max_concurrency());
    arena.execute([]() {
        puts("isolated task");
    });
    return 0;
}
```

When I run it with debug TBB 2020 Update 3, I get:
```
TBB interface version 11103
requesting global_control 1
max_concurrency after global_control 1
max_concurrency after enqueue 2
TBB Warning: The number of workers is currently limited to 0. The request for 1
workers is ignored. Further requests for more workers will be silently ignored u
ntil the limit changes.

isolated task
```
When I comment out the static task_scheduler_init object, I get this output
```
TBB interface version 11103
requesting global_control 1
max_concurrency after global_control 8
max_concurrency after enqueue 8
isolated task
```

Unfortunately, the 4 parts of this program (the use of task_scheduler_init, global_control, enqueue, task_arena) are in 4 separate libraries in our application that results in the debug output. I'm not sure what should be happening here but it feels like something might be off in TBB? I'm not even sure which library is at fault here because individually, they seem to be doing reasonable things at each step.

**Comment by e4lam** [comment]
Bizarrely, the (release?) TBB 2020.3 version on godbolt behaves differently when the task_scheduler_init object is commented out:
https://godbolt.org/z/Gh5dKvEzj
```
TBB interface version 11103
requesting global_control 1
max_concurrency after global_control 2
max_concurrency after enqueue 2
isolated task
```

**Comment by e4lam** [comment]
Note that if you're trying this on godbolt, it only runs in a VM of 2 threads (ie. `tbb::task_scheduler_init::default_num_threads()` returns 2).

So a side problem here is shouldn't `tbb::this_task_arena::max_concurrency()` return the effective value of how many threads can be used?

**Comment by alexey-katranov** [comment]
There are really complex interoperability between those four interfaces:
1. `global_control` affects only the internal thread pool. `global_control::max_allowed_parallelism` specifies how many threads are allowed at a particular time (when the control is active).
2. `tbb::task_scheduler_init` affects the behavior of the current thread. It creates an implicit arena with the specified concurrency. So, attached `task_arena` will have the specified concurrency because it will be attached to the implicit arena created with `tbb::task_scheduler_init`.
3. `task_arena` has a fixed concurrency specified at initialization time. Either it is specified with `tbb::task_scheduler_init` or with the constructor argument, it will be fixed for the lifetime of the `task_arena.` Therefore, `task_arena::max_concurrency()` returns the maximum number of threads that can join the `task_arena`. It does not matter how many threads are inside internal thread pool because user can join external threads with `task_arena::execute` but `max_concurrency` cannot be exceeded (beside the `enqueue` case).
4. `task_arena::enqueue` allows creating a task that user is not obligated to wait. It means that at least one thread should be allocated to proceed enqueue tasks. The most complex case when internal thread pool has no workers or `task_arena` has serial concurrency (i.e. only the main thread). In such scenario, the enqueue task triggers so call mandatory concurrency mechanism that creates additional thread in internal thread pool (even if `global_control::max_allowed_parallelism==1`) and the concurrency of `task_arena` is increased to 2.

**Comment by e4lam** [comment]
Thanks, Alexey!

The purpose for `tbb::task_arena arena(tbb::this_task_arena::max_concurrency());` was so avoid using more concurrency than specified `task_scheduler_init` because it was observed that default values would end up using more threads than expected. All this in code prior to the introduction of `global_control`.

So what I'm hearing is that the effective max concurrency now is `min(global_control::active_value(global_control::max_allowed_parallelism), this_task_arena::max_concurrency())`. While the old code would still behave the same since `global_control` would override the maximum concurrency, it would cause extraneous debug print outs so we should be now using this expression instead. Is this correct?

**Comment by e4lam** [comment]
On second thought though, generally algorithms should care about `global_control` so it seems a bit odd that we're printing out a printf for this.

**Comment by pavelkumbrasev** [comment]
Hi @e4lam Is this issue still relevant?

**Comment by e4lam** [comment]
It's just annoying that we have debug prints for this because in an ecosystem of libraries using TBB (ie. the [VFX Platform](https://vfxplatform.com)). The application can be limiting the number of threads, the libraries can be requesting some level of natural max concurrency and we get these print outs as a result on debug builds when they're not issues at all.

**Comment by pavelkumbrasev** [comment]
What about proposed by you solution is it work in your case?
```
const int max_concurrency = std::min(global_control::active_value(global_control::max_allowed_parallelism), this_task_arena::max_concurrency());
tbb::task_arena arena(max_concurrency);
```
It should work fine in terms of debug prints.

**Comment by e4lam** [comment]
No, it does not because the code creating the arena is in some third party library. Individually, each library is doing something reasonable, but altogether, it results in the extraneous debug output.

**Comment by nofuturre** [comment]
@e4lam is this issue still relevant?

**Comment by e4lam** [comment]
I guess not since you guys have removed `tbb::task_scheduler_init`.
