### ISSUE TITLE
TBB_USE_EXCEPTIONS macro should be defined by build process

### ISSUE THREAD

**Issue by aggieNick02** [oneapi-src/oneTBB#414]
`TBB_USE_EXCEPTIONS` is used in both headers and cpp files. This means that if you build TBB with it off and then want to use that built library, you need to make sure to also set it off in the client for the correct parts of the headers to be included.

If the client uses one value and the built library another, you will get wrong behavior/asserts/aborts. It would be great if the value used at library build time was exported to a generated header so that the client need not worry about it.

I had been using a TBB built with exceptions off, and manually set `TBB_USE_EXCEPTIONS=0` to get the right behavior. Later I switched to a build of the library with exceptions on, having forgotten I had set `TBB_USE_EXCEPTIONS=0`, and spent a good deal of time confused by assert/aborts in the TBB scheduling algorithms

**Comment by alexey-katranov** [comment]
Do you use TBB or oneTBB? oneTBB library is not supported to be built with `TBB_USE_EXCEPTIONS=0` while users can specify `TBB_USE_EXCEPTIONS` when compiling application code.

**Comment by aggieNick02** [comment]
I'm sorry, I didn't realize there was a difference between TBB and oneTBB. I'm using oneTBB (the TBB present in this github repo). I'm guessing TBB is the previous version, and oneTBB is current. Are you saying that TBB supported building the library with `TBB_USE_EXCEPTIONS=0` but that is no longer supported in oneTBB?

**Comment by alexey-katranov** [comment]
It was possible to build TBB runtime with `TBB_USE_EXCEPTIONS=0`; however, it was neither supported nor tested. Such build was incompatible with officially or normally built version and use-cases were unclear (it still had a dependency on C++ runtime). 

In oneTBB, we decided to focus on use case when user wants to build their application without exceptions and rtti. So, the runtime is not configurable in that manner; however, user can mix different components (that need exceptions and not) in one application or use [`global_control::terminate_on_exception`](https://spec.oneapi.com/versions/latest/elements/oneTBB/source/task_scheduler/scheduling_controls/global_control_cls.html#_CPPv4N9parameter22terminate_on_exceptionE) to enforce terminate instead of exceptions for all componets.

**Comment by aggieNick02** [comment]
Ah, ok. That is helpful to know. I think that makes this bug irrelevant. I did not realize setting the macro for building was unsupported in oneTBB - I had added support for that in the vcpkg port (https://github.com/microsoft/vcpkg/tree/master/ports/tbb), so I'll follow up and remove it.

**Comment by aggieNick02** [comment]
I'm pushing the change to the vcpkg port changes today to remove what I had added before. But I just wanted to clarify - the runtime sure seemed to still be configurable and build/run "fine" setting `TBB_USE_EXCEPTIONS=0`. Is there supposed to be something in oneTBB now to stop that from being able to happen, or is it more just moving to a more explicit "not supported" stance if someone should try to build the runtime with it set, if that makes sense?

My use-case was wanting to terminate on exception for debugging purposes, so if there is something like `global_control::terminate_on_exception` (I did not realize that was a thing I could configure), I'm happy to have that easily available instead of having to tweak and custom build the runtime.

**Comment by alexey-katranov** [comment]
> Is there supposed to be something in oneTBB now to stop that from being able to happen, or is it more just moving to a more explicit "not supported" stance if someone should try to build the runtime with it set, if that makes sense?

It was intentional decision to drop `TBB_USE_EXCEPTIONS=0` support for the oneTBB runtime. We do not see the value for the runtime built without exceptions. It might slightly reduce the code size; however, the dependency on C++ runtime is still remain. Moreover, the additional configuration requires effort to support and test. Additionally, it is incompatible if used with another runtime build with other setting. 

However, there is some benefits for users if we support `TBB_USE_EXCEPTIONS=0` for header files that user can built their application without exceptions and rtti. In that case they cannot catch unexpected exception from oneTBB runtime, so we introduced special global control to cause termination in the case of possible exception.

If you still believe that supporting `TBB_USE_EXCEPTIONS=0` for oneTBB runtime makes sense for some use cases, please, share your thoughts that we can reconsider our decision.

**Comment by isaevil** [comment]
Seems like the problem is solved. If any other questions are left, feel free to reopen this issue.
