### ISSUE TITLE
How to build for iOS using cmake?

### ISSUE THREAD

**Issue by shlowdy** [oneapi-src/oneTBB#491]
with
cmake . -DCMAKE_BUILD_TYPE=Release -DTBB_TEST=Off
cmake --build . 
I got some macOS dylibs

How to build for iOS?

**Comment by kmeisthax** [comment]
CMAKE has a specific flag for this: `-DCMAKE_SYSTEM_NAME=iOS`, as documented in https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-ios-tvos-or-watchos

Your issue actually helped me, though, because I needed `-DTBB_TEST=Off` to get the `TRY_RUN` error to go away. With that and this TBB appears to build correctly now. Or, at least, I'm getting errors from other dependencies instead of TBB. (For context, I'm trying to cross-compile Blender to iPadOS, and I have like 20 broken deps I'm trying to get to build)

**Comment by AlexVeprev** [comment]
@kmeisthax, thank you for the investigation! BTW.  setting `THREADS_PTHREAD_ARG` to `0` may help to resolve `try_run` issue in case of cross-compilation: see for example: https://github.com/oneapi-src/oneTBB/blob/master/cmake/toolchains/mips.cmake#L33
