### ISSUE TITLE
Hugepage feature error in SamSung Galaxy S20 Ultra 5G

### ISSUE THREAD

**Issue by John-Yi** [oneapi-src/oneTBB#584]
our app will crash at branch Master src/tbbmalloc/tbbmalloc_internal.h line 457: 
```c
if (thpPresent == 'y') {
    MALLOC_ASSERT(hugePageSize != 0, "Huge Page size can't be zero if we found thp existence.");
    thpAvailable = true;
}
````
I use adb shell to check this phone, the file `/sys/kernel/mm/transparent_hugepage/` is exist. But cat the `/proc/meminfo`, can't find out key word:`Hugepagesize`, only got a similar word: `HugepagePool`
![image](https://user-images.githubusercontent.com/57124066/134445751-547b30aa-4893-4ef8-9956-16f06502a7cc.png)
Is it possible some phone use another word instead of TBB's key word:`Hugepagesize`?

**Comment by isaevil** [comment]
`tbbmalloc` relies on `Hugepagesize` variable availability because it seems to be common on Linux systems (I think it is applicable for Android too). I guess Samsung modified Android kernel for its phones somehow because I didn't find any references to `HugepagePool` variable except of kernel codes for Samsung phone on GitHub.
@alexey-katranov please correct me if I am wrong somewhere

**Comment by alexey-katranov** [comment]
To tell the truth, I do not know how `Hugepagesize` is common. However, the crash is not expected if `Hugepagesize` is not present. I believe it should be deny of service (i.e. do not use huge pages) if the key word is not available.

**Comment by John-Yi** [comment]
thx for reply. @isaevil @alexey-katranov  Will you release an official version to fix this error?

**Comment by isaevil** [comment]
Closing since https://github.com/oneapi-src/oneTBB/pull/594 is merged.
