### ISSUE TITLE
Why onetbb not like static library?

### ISSUE THREAD

**Issue by zhanglistar** [oneapi-src/oneTBB#646]
![image](https://user-images.githubusercontent.com/985418/141080298-4fee17a8-3a37-454b-9ec3-f4cbc2469443.png)

When I do 
`cmake -DBUILD_SHARED_LIBS=OFF ..
`

What's the problem with static library?

Thanks for your reply.

**Comment by alexey-katranov** [comment]
The static library is not a problem itself; however, there are some scenarios when the static linkage approach can lead to the issues. The most typical problem if static and dynamic or static and static libraries are mixed in one application. In the good case, it will be a performance problem, in the worst case, something will mysteriously fail (e.g. due to symbol conflicts).
Based on our experience with Intel OpenMP runtime (that provides and tries to support static build), we faced a lot of performance and correctness issues due to user configurations.

Therefore, we do not recommend using the static library. If you are Ok to cope with possible and unforeseen issues, we do not block the static build (in any case, it is an open source and any block can be removed). Moreover, we can consider reasonable improvements even for the static configuration if it can help someone.

**Comment by zhanglistar** [comment]
> The static library is not a problem itself; however, there are some scenarios when the static linkage approach can lead to the issues. The most typical problem if static and dynamic or static and static libraries are mixed in one application. In the good case, it will be a performance problem, in the worst case, something will mysteriously fail (e.g. due to symbol conflicts). Based on our experience with Intel OpenMP runtime (that provides and tries to support static build), we faced a lot of performance and correctness issues due to user configurations.
> 
> Therefore, we do not recommend using the static library. If you are Ok to cope with possible and unforeseen issues, we do not block the static build (in any case, it is an open source and any block can be removed). Moreover, we can consider reasonable improvements even for the static configuration if it can help someone.

Thanks for your reply.
