### ISSUE TITLE
Memory allocation/dealloction

### ISSUE THREAD

**Issue by erling-d-andersen** [oneapi-src/oneTBB#689]
When I run my application using Inspector I see

![image](https://user-images.githubusercontent.com/10224241/146375393-f5771373-98bf-4d1a-85b4-1a9d7a7eec72.png)

Not sure if that is a bug or Inspector getting it wrong.

**Comment by erling-d-andersen** [comment]
Will the dump include our source?

We can also build TBB from source ourselves. Would that help?

**Comment by alexey-katranov** [comment]
> Will the dump include our source?

You need to remove `-include-sources` from command line. If you have a concern about exposing the sources, you can share the result via `inteltbbdevelopers@intel.com`.

If the email option is not suitable for you, we can try another variant. Can you take some [official build](https://github.com/oneapi-src/oneTBB/releases) of oneTBB and expand the result to get the addresses where allocation and deallocation routines are called inside `tbb12_debug.dll` (we can try to use the debug info to track what happens). Or maybe some callstacks are reported by Inspector (you can cut off the sensitive functions (if any) from the log)

**Comment by erling-d-andersen** [comment]
I have emailed the requested file.

**Comment by MichaelTutin** [comment]
We have reproduced this problem in Inspector. It seems that it doesn't correctly detects allocator type (new/delete) inside of tbb_debug.dll if it fails to locate symbol file of this module during analysis run (tbb_debug.pdb should be in the same folder as tbb_debug.dll).
Could you please check if it matches your scenario?

Meanwhile I've submitted that issue to Inspector project.

**Comment by erling-d-andersen** [comment]
Your suggested fix seems to remove the error message.

**Comment by anton-potapov** [comment]
@erling-d-andersen can we close this ?

**Comment by erling-d-andersen** [comment]
Yes.

I see 

ID		Type	Sources	Modules	Object Size	State
		Memory leak	allocator.cpp:190	tbb12_debug.dll	96864	Not fixed

Is that something you want to take a look at?

**Comment by alexey-katranov** [comment]
As for memory leak, I suspect that it is related to process shutdown that the OS kills oneTBB worker threads and they are unable to deallocate internal structures. Overall, it is not an issue because the OS cleans up everything automatically. So, if the memory consumption is not growing during execution time, the report about the leak can be ignored (it is difficult to teach the tool to differentiate missed deallocations during shutdown from real leaks)

To be sure that it is not a real leak, can you please share the callstack where allocation is performed (feel free to hide your application frames - they are not required).

**Comment by erling-d-andersen** [comment]
I will open a new issue if I conclude it is leaking.
