### ISSUE TITLE
What is the difference between tbb::atomic and std:atomic

### ISSUE THREAD

**Issue by MaxPHPer** [oneapi-src/oneTBB#694]
hello everyone, 
      I don't know the difference between tbb::atomic and std:atomic. 
      Is tbb::atomic more efficient than std::atomic?

      In addition, I cannot find the corresponding document by searching such word "tbb::atomic", such as 
[https://oneapi-src.github.io/oneTBB/search.html?q=tbb%3A%3Aatomic](url)

     If you know it, please give me some help and thank you in advance

**Comment by MaxPHPer** [comment]
sorry, I have known that tbb::atomic was deprecated now.

**Comment by alexey-katranov** [comment]
`tbb::atomic` was introduced when C++11 atomics were not invented yet. However, with C++11 `tbb::atomic` became obsolete and did not bring any value. Overall, C++11 atomics can be more efficient than `tbb::atomic` because they are recognizable by modern compilers and some additional optimization might take place.

**Comment by MaxPHPer** [comment]
> `tbb::atomic` was introduced when C++11 atomics were not invented yet. However, with C++11 `tbb::atomic` became obsolete and did not bring any value. Overall, C++11 atomics can be more efficient than `tbb::atomic` because they are recognizable by modern compilers and some additional optimization might take place.

thank you very much!!！
