### ISSUE TITLE
Casting a TBB Node (Source Node or Function Node)

### ISSUE THREAD

**Issue by Veronizlada** [oneapi-src/oneTBB#818]
Hello, suppose I have a base class called Animal and child class of Animal called Cat:

class Animal
{
public:
    Animal() = default;
    virtual ~Animal() = default;
};

class Cat : public Animal
{
public:
    Cat() = default;
};

template<typename T>
using node = tbb::flow::input_node<T>

**(How?) Can I do something like please?**

std::shared_ptr< node < Animal > > pAnimal= std::make_shared< node < Cat > > (g, function);
const std::shared_ptr< node < Cat > > pCat = std::dynamic_pointer_cast< node < Cat > >(pAnimal); 

Your answer is appreciated, thanks very much!

**Comment by vlserov** [comment]
You can use `tbb::flow::graph_node`. It's base class for all flow graph nodes.

```
using namespace tbb::flow;
std::shared_ptr< graph_node > pAnimal = std::make_shared< input_node<Cat> >(g, function);
const std::shared_ptr< graph_node > pCat_Node = std::dynamic_pointer_cast< input_node<Cat> >(pAnimal);
...
const std::shared_ptr< input_node<Cat> > pCat = std::dynamic_pointer_cast< input_node<Cat> >(pAnimal);
```

**Comment by Veronizlada** [comment]
Thanks a lot @Vladimir Serov. I think this solves the problem and answers my question. Please don't worry about my next question, but if anyone has time, would be very greatful if you can check:

On a different subject, how does std::dynamic_pointer_cast work, is it fast to use? Does it create a copy of the node somewhere when casting?

**Comment by vlserov** [comment]
`std::dynamic_pointer_cast` is `dynamic_cast` with `std::shared_ptr`, so it doesn't create a copy of the node.
`std::dynamic_pointer_cast` is slower than `std::static_pointer_cast`, because of runtime check of possibility casting pointer to provided type.
But if `std::shared_ptr` is used as reference count and holds only specific type, like `pAnimal` in example above holds reference on the `input_node<Cat>`, it's better to use `std::static_pointer_cast`.

**Comment by Veronizlada** [comment]
Great, thx very much!
