### ISSUE TITLE
Serial Does not mean Order: What to do?

### ISSUE THREAD

**Issue by Veronizlada** [oneapi-src/oneTBB#829]
Hello, I just discovered (sadly) that putting Serial in a node has nothing to do with the order of the received message, which I totally understand and couldn't think of a way to control this. However, one can use sequencer_node, I am just wondering if the sequencer has to be a sequence or just has to return a std::size_t? Meaning can I put timestamp converted to seconds in a sequencer? I want to order by time? E.g. 

Sequence of messages can be 1,2,3,4,5,6... But can it be 2,5,7,8,10,122? Two answers here are possible:
1. No sequencer has to be increasing by 1.
2. Sequence has just to be increasing, sequencer_node will guarantee the order.
It's likely that the answer is 1. as there is no way that the sequencer would know if it has to wait if there is more old msg or send the current one unless the step of the sequence == 1.

Could you please help answer my question? Thanks for taking the time reading this.

If 2. is the case which is very likely could you please help solve this problem and sequence stuff with machine timestamp? Of course priority_queue wouldn't work as msgs could be passed immediatly and not queued :)

**Comment by vossmjp** [comment]
A serial function node does maintain a queue at its input; so messages sent from the same thread will be processed in the order that they are put to the serial function_node from that thread. However, if multiple threads are putting messages to the function_node concurrently, there is no specific order between the threads. So, depending on your use case, this may be sufficient. 
But you are right that if you use a sequencer_node to reestablish a global ordering before the serial function_node, that node requires a sequence increasing by 1. And you also need to set the function_node to be rejecting since otherwise the messages will flow immediately through the sequencer node into the function_node’s queue. One way to create this global ordering is assign to the sequence number at the time you would normally acquire the timestamp. For example, using an atomic counter. So, for example, if you have messages that you want to output in the same order they were received earlier in the graph, assign the sequence number at the time the message is first received in the graph. Or two, pass the item through a node (perhaps an inline function node since this will be a short operation) that assigns a sequence number based on your time stamp. As you rightly point out, you would need to determine how to properly assign a sequence number based on the time stamp since there’s no general way to determine which time stamps are skipped.
But again, if your timestamp is simply the time the message arrived at the serial function_node, the embedded FIFO queue in the function_node might be enough for you.

**Comment by Veronizlada** [comment]
thanks so much

**Comment by kboyarinov** [comment]
@Veronizlada, I will close this issue for now.
Feel free to re-open it or create a separate one if necessary.

**Comment by sdebionne** [comment]
I hope it's OK to resurrect this question. I have the following graph:

`input_node` - > `function_node (serial, lightweight)` - > `multifunction_node`

and was quite surprised that the data arrives unordered in the mutlifunction_node. The graph runs in the default arena (so many threads). I had to insert a sequencer in front of the `multifunction_node`.

Is there any combination of policy/concurrency that would help to keep the data ordered after middle `function_node` ?
