### ISSUE TITLE
concurrent_hash_map::size() is slow?

### ISSUE THREAD

**Issue by willkk** [oneapi-src/oneTBB#854]
http://www.cis.uoguelph.ca/~wgardner/intel_docs/compilers/tbb/html/a00103.html#75bb57a153952ffadfcf2e4c73deabb1
![企业微信截图_1657531891468](https://user-images.githubusercontent.com/17777977/178234399-e662b949-9494-4bb2-a44b-a8d0f08777ac.png)
Is it right? I check the code and find that concurrent_hash_map uses an atomic variable to store member's count. It should be very fast, right?
And another question. Can size()  method be used in an accessor scope? Sample code:

```c++
tbb::concurrent_hash_map<std::string, XXX> task_map;
ConstAccessor ca;
std::string task_id;
if (task_map.find(ca, task_id)) {
  task_map.erase(ca);
}
...
LXINFO("task size:", task_map.size());
```

**Comment by kboyarinov** [comment]
@willkk,

It seems like this documentation is outdated and can differ with the actual oneTBB state.
I would suggest to use [oneTBB specification](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/nested-index.html) and [oneTBB Developer guide](https://oneapi-src.github.io/oneTBB/) to obtain the latest documentation.

As for the ``concurrent_hash_map::size()`` method - you are right, this method only reads the atomic field of concurrent_hash_map, so I would not expect any significant overheads on using it in serial or concurrent parts of the application. The difference between serial STL container ``size()`` method and ``concurrent_hash_map::size()`` method should not be more significant then the difference between reading the atomic and non-atomic variable.

And the last part regarding using ``size()`` in accessor scope - in terms of the container state, this method is safe to be used in concurrent environment. It means that use of ``size()`` in accessor scope cannot result in broken container. BUT this is important to note that the returned value of this method can differ from the expected one while using it concurrently. It means that the returned number of elements can differ from the actual number, because of other threads performing insertions/removals. So it can be used for just receiving and printing the information (as in your code snippet) is OK, but I would not recommend to build some important logic on top of that due to unpredictable result of concurrent ``size()``.

**Comment by willkk** [comment]
Thank you so much.
