### ISSUE TITLE
Help needed with linking tbb built from source

### ISSUE THREAD

**Issue by ikabadzhov** [oneapi-src/oneTBB#861]
Hello, I am trying to benchmark the performance of TBB on a remote machine (no sudo).
I tried to build it from source, closely following the installation guideline: https://github.com/oneapi-src/oneTBB/blob/master/INSTALL.md#example-of-installation.
TBB was successfully build and installed.

I had this minimal checker to see if I installed tbb successfully:
```cpp
#include "tbb/task_group.h"  
#include <iostream>

using namespace tbb;

int Fib(int n) {
    if( n<2 ) {
        return n;
    } else {
        int x, y;
        task_group g;
        g.run([&]{x=Fib(n-1);}); // spawn a task
        g.run([&]{y=Fib(n-2);}); // spawn another task
        g.wait();                // wait for both tasks to complete
        return x+y;
    }
}

int main(){
   std::cout << Fib(10) << std::endl;
}
```

I successfully compiled this with:
```
$ g++ -g -Wall -Wextra -Wpedantic -O3 min.cpp -o min -I/tmp/oneTBB/include -L/tmp/my_installed_onetbb/lib64/ -ltbb
```
(I have also tried `-I/tmp/my_installed_onetbb/include` but this had the same effect)
Then trying to execute, I receive:
```
$ ./min
./min: error while loading shared libraries: libtbb.so.12: cannot open shared object file: No such file or directory
```

I cannot see what am I missing.

**Comment by kboyarinov** [comment]
@ikabadzhov 

The problem is that your operation system is not aware on where the dynamic oneTBB library is located.
You can either update the `LD_LIBRARY_PATH` environment variable manually:

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/tmp/my_installed_onetbb/lib64` 

or use the `vars.sh` script which is located in the `build` directory of the original oneTBB repository. In my case it is

`source /tmp/oneTBB/build/gnu_11.2_cxx11_64_relwithdebinfo/vars.sh`

**Comment by ikabadzhov** [comment]
This was exactly what I was looking for. Thank you @kboyarinov !
