### ISSUE TITLE
'_MCW_DN' was not declared in this scope

### ISSUE THREAD

**Issue by Du-Xinyi** [oneapi-src/oneTBB#863]
I use mingw(version:8.1) to compile with cmake. Cmake works fine, but this problem occurs at Generate. What should I do
![U$K_V7JSSBP3DSC6$ QC$~1](https://user-images.githubusercontent.com/73220784/182137401-81a0d2c5-9241-44b8-afd6-28169f00b381.png)

**Comment by kboyarinov** [comment]
@Du-Xinyi, thank you for reporting the issue
I was able to reproduce it on my side and found that `_MCW_DN` and other `float.h` stuff are provided by MinGW only when `__STRICT_ANSI__` macro is not defined.
This problem moves away when compiling with `-U__STRICT_ANSI`.
But unfortunately, I saw other problems with oneTBB build using MinGW.

Currently, MinGW is outside of oneTBB [support matrix](https://github.com/oneapi-src/oneTBB/blob/master/SYSTEM_REQUIREMENTS.md#:~:text=Android*%209-,Supported%20Compilers,Clang*%206.0.0%20%2D%2012.0.0,-Footer), so I would not consider this as a oneTBB issue.
You can submit a PR to the oneTBB repo if you want this issue to be fixed in oneTBB product.

**Comment by isaevil** [comment]
@MehdiChinoune @jschueller could you please take a look?

**Comment by jschueller** [comment]
retry with v2021.6.0, that one is ok, I use a more recent mingw though (10.0.0 / gcc 12)

**Comment by isaevil** [comment]
@Du-Xinyi seems like it works on newer versions of MinGW. Please reopen issue if your problem persists.

**Comment by MehdiChinoune** [comment]
Fixed by https://github.com/mingw-w64/mingw-w64/commit/c6e13e0c105eab7797c2373819b49fff6b05566c, So you need mingw-w64>=8.0.1
The MINGW GCC 8.1.0 compiler from https://sourceforge.net/p/mingw-w64 was built against mingw-w64 6.0.0
