### ISSUE TITLE
LINK : fatal error LNK1104: cannot open file 'tbb12_debug.lib'

### ISSUE THREAD

**Issue by Veronizlada** [oneapi-src/oneTBB#871]
Hello, 

Could you please help me solve this issue, I am getting this issue when I build my solution in VS:

LINK : fatal error LNK1104: cannot open file 'tbb12_debug.lib'

Should I build the Tbb lib and generate the .lib? If yes isn't there a way to work with hpp only?

I don't want to only use the binaries :) I want the library copied in my folder.

Could you please help me? I have built the library in the past (3/4 months ago and all was good, but just confirming that I have to build the library and there is no way around (exept binaries)). I also don't remember how I built it :)

Thanks!

**Comment by kboyarinov** [comment]
@Veronizlada,

I would suggest to build or get the pre-built one from one of [oneTBB releases for Windows](https://github.com/oneapi-src/oneTBB/releases) because almost all the functionality uses .lib, such as `parallel_for` and other parallel algorithms as well as Flow Graph.
Some of TBB features are mostly header-based, but still uses .lib for exception handling, extra assertions and other stuff.
And also there is no guarantee that the functionality that is header-based today will not use the library in the future releases.

**Comment by isaevil** [comment]
@Veronizlada is this issue still relevant for you? Could you please respond?

**Comment by isaevil** [comment]
Closing it since no response.
