### ISSUE TITLE
Apple Silicon (M1, M1Pro) support for QoS

### ISSUE THREAD

**Issue by bubnikv** [oneapi-src/oneTBB#896]
Apple Silicon M1 processors are equipped with 4 high efficiency and 4 high performance core. TBB does not make any effort as to hint the operating system on which core to schedule a task. The default behavior leads to an unfortunate results, where long running tasks may be scheduled to slow high efficiency cores leaving the high performance cores idle if the operating system decides that the task executed is not interactive enough. The scheduling behavior is often detrimental to the application performance if other tasks depend on the result of the task scheduled on the slow core.

First, we likely want to adjust the thread QoS level on thread pool thread creation, as the "Default" QoS thread attribute may not be ideal. 

https://developer.apple.com/library/archive/documentation/Performance/Conceptual/power_efficiency_guidelines_osx/PrioritizeWorkAtTheTaskLevel.html

> The priority level of "Default" QoS falls between user-initiated and utility. Work that has no QoS information assigned is treated as default. The GCD global queue runs at this level. This QoS is not intended to be used to classify work.

Most likely we want to set the QoS level of a thread pool thread to "User-initiated" and I expect that the operating system will then re-schedule a thread from high efficiency to a high performance core once a high performance core becomes idle.

Second, in TBB there is an undocumented affinity_helper class, which may or may not set thread affinity, locking a thread to a slow high efficiency core. Frankly reading the code I am not sure what is the purpose of the helper class and whether it kicks in or not.

Intel is pushing the big.little concept forward with the Alder Lake architecture, thus I expect that TBB will have similar issues on such CPUs.

**Comment by pavelkumbrasev** [comment]
Hi @bubnikv, I did not fully understand the "First" suggestion. Do you suggest pass additional argument on threads creation on Apple system? 
Second one, affinity_helper uses to respect affinity mask that was assigned to process if I am not mistaken. oneTBB on its own does not bind any thread until user explicitly ask about that via for example TBBBind interface.

Also, applications that use oneTBB properly (in our example with different core types) will automatically benefit from dynamic nature of oneTBB task-scheduler, because work stealing enables good load balancing for such CPU's. Proper use oneTBB on such CPUs means not creating one single big piece of work (task) for each thread, but creating much more smaller tasks which oneTBB threads would then distributed dynamically, so that faster cores execute more tasks.

**Comment by bubnikv** [comment]
> Hi @bubnikv, I did not fully understand the "First" suggestion. Do you suggest pass additional argument on threads creation on Apple system?

No, I would just configure the thread on creation to use the CPU to its full extent. I suppose the purpose of the TBB thread pool is to accelerate processing as much as possible, thus the simple strategy is meaningful.

> Second one, affinity_helper uses to respect affinity mask that was assigned to process if I am not mistaken. oneTBB on its own does not bind any thread until user explicitly ask about that via for example TBBBind interface.

Thanks. That means it is the macOS system that maintains the thread affinity to the low performance core for the default QoS thread configuration.

> Also, applications that use oneTBB properly (in our example with different core types) will automatically benefit from dynamic nature of oneTBB task-scheduler, because work stealing enables good load balancing for such CPU's. Proper use oneTBB on such CPUs means not creating one single big piece of work (task) for each thread, but creating much more smaller tasks which oneTBB threads would then distributed dynamically, so that faster cores execute more tasks.

We understand that and your argument is certainly valid. Most of our tasks are trivially parallelizable and we did our homework. However some tasks are inherently serial and their parallelization may be difficult to do efficiently. In our case, we have a handful of serial tasks that we may execute in parallel, where some finish earlier than others. Those tasks often end up being scheduled to the low performance cores.

**Comment by pavelkumbrasev** [comment]
In your case you can try to use task_arena constraints - [specification link](https://spec.oneapi.io/versions/1.1-rev-1/elements/oneTBB/source/task_scheduler/task_arena/task_arena_cls.html). You could create task_arena and decide which tasks would be executed on performance CPUs and which not.
If HWLOC is available on your system you should be able to build the TBBBind. (Read cmake [readme ](https://github.com/oneapi-src/oneTBB/blob/master/cmake/README.md) how to build it)
This feature doesn't tested on Apple M1 due to it is community support if I am not mistaken.

**Comment by pavelkumbrasev** [comment]
In my point of view with current oneTBB design the solution with `task_scheduler_observer` + user_callback (with a thread_local) seems good.
Also you can suggest a patch with you think should be done in oneTBB via PR.

**Comment by bubnikv** [comment]
@pavelkumbrasev Thanks, we will consider using the proposed solution.
I would love to provide a patch but frankly the code is highly non trivial.

We are using 
```tbb::enumerable_thread_specific<bool, tbb::cache_aligned_allocator<bool>, tbb::ets_key_usage_type::ets_key_per_instance>```
for our locales flag, however I wonder how costly it is. It would be great if the cost of the thread local storage abstraction was documented. I worry that for small tasks the cost of TLS abstraction could be substantial.

**Comment by pavelkumbrasev** [comment]
In my understanding of `enumerable_thread_specific` after the first touch via `ets.local()` there should not be much overhead over standard TLS.
You might also try to use [thread_local](https://en.cppreference.com/w/cpp/keyword/thread_local) it should works in your case too.

**Comment by bubnikv** [comment]
@pavelkumbrasev 

Thanks Pavel. I agree that for parallel for loops enumerable_thread_specific is fine, it executes the callback on each thread entering the parallel_for just once.

However we have found out that for tbb::parallel_pipeline() the callback is called every time a task gets executed by the parallel_pipeline, thus the callback gets called many times over the same thread. In our particular case the tasks processed by parallel_pipeline are large enough, however there is a room for improvement IMHO.
