### ISSUE TITLE
Perf issue

### ISSUE THREAD

**Issue by amallia** [oneapi-src/oneTBB#90]
I am doing some `perf` analysis and get into a point where the following has a big impact on performance:
```
       │                                                                                                                                                                 ▒
       │     //TODO: check if use of gcc __builtin_ia32_pause intrinsic gives a "some how" better performing code                                                        ▒
       │     static inline void __TBB_machine_pause( int32_t delay ) {                                                                                                   ▒
       │         for (int32_t i = 0; i < delay; i++) {                                                                                                                   ▒
 71.19 │       add    $0x1,%eax                                                                                                                                          ▒
  3.33 │       cmp    %eax,%ecx                                                                                                                                          ▒
       │     ↑ jne    25260 <tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::receive_or_steal_task(long&, long)+0x250>                             ▒
       │     _ZN3tbb8internal14atomic_backoff13bounded_pauseEv():                                                                                                        ▒
       │         //! Pause for a few times and return false if saturated.                                                                                                ▒
       │         bool bounded_pause() {
```

What's the problem here?

**Comment by anton-malakhov** [comment]
I suppose your statistics is aggregated across multiple threads like "user" time metrics, isn't it? This is the code for busy-waiting loops, which are used for synchronization between threads and are likely in two common cases, which would be obvious if you had a stack info for these hot-spots:
1) when a thread has no work to do, it tries to find it until enough attempts are made. This indicates load imbalance, low parallelism in application, or just the fact that your TBB worker threads are kept ready to get to a work as soon as it arrives. Using VTune Amplifier, I usually filter by master thread in order to see critical application path, which is what you ultimately want to optimize (the "real" time). So, there is no impact on performance from this `__TBB_machine_pause` code but it might indicate insufficient parallelism.
2) on a lock contention - when a tbb spin mutex used and multiple threads contending for acquiring it. Same as above, there is no impact on performance from `__TBB_machine_pause` but it indicates that there is a contention problem elsewhere.

**Comment by aleksei-fedotov** [comment]
Closing the issue as addressed. Please reopen if you think it is not the case and you have further questions to clarify.
